# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(auto_now=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('D', 'Not Reviewed'), ('P', 'Published'), ('E', 'Expired')], default='D', max_length=1),
        ),
    ]
