# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160201_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='keyword_set', to='blog.Tag', verbose_name='the related tags'),
        ),
    ]
