# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import userprofiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=userprofiles.models.get_image_path),
        ),
    ]
