# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160201_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
